# Generated by Django 3.1.7 on 2021-03-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0008_t'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='t',
            new_name='t1',
        ),
    ]
