# Generated by Django 3.1.7 on 2021-03-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0009_auto_20210322_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t1',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
