# Generated by Django 3.1.7 on 2021-04-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0011_about_butn_cont_foll_like_mesg_page_postjob_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
