# Generated by Django 3.1.7 on 2021-04-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0012_page_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='pid',
        ),
        migrations.AlterField(
            model_name='page',
            name='hour',
            field=models.CharField(default='Unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='page',
            name='loct',
            field=models.CharField(default='varanasi', max_length=500),
        ),
        migrations.AlterField(
            model_name='page',
            name='webs',
            field=models.CharField(default='google.com', max_length=500),
        ),
    ]
