# Generated by Django 3.1.7 on 2021-04-03 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0013_auto_20210403_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='page',
            name='loct',
        ),
        migrations.RemoveField(
            model_name='page',
            name='webs',
        ),
    ]
