# Generated by Django 3.1.7 on 2021-04-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0015_auto_20210403_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='channel_art',
            field=models.ImageField(default='dp.png', upload_to='channel/'),
        ),
        migrations.AddField(
            model_name='page',
            name='channel_icon',
            field=models.ImageField(default='g.png', upload_to='profile/'),
        ),
    ]
