# Generated by Django 3.1.7 on 2021-04-05 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0016_auto_20210405_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='channel_art',
            new_name='page_art',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='channel_icon',
            new_name='page_icon',
        ),
    ]
