# Generated by Django 3.1.7 on 2021-04-07 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0018_auto_20210406_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbs.about'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
