# Generated by Django 3.1.7 on 2021-04-07 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0019_auto_20210407_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbs.page'),
        ),
    ]
