# Generated by Django 3.1.7 on 2021-04-07 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0020_auto_20210407_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pid',
        ),
        migrations.AddField(
            model_name='post',
            name='did',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sbs.page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
