# Generated by Django 3.1.7 on 2021-04-07 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0021_auto_20210407_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='did',
            new_name='pid',
        ),
    ]
