# Generated by Django 3.1.7 on 2021-04-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0022_auto_20210407_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
