# Generated by Django 3.1.7 on 2021-04-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0027_auto_20210407_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='id',
            new_name='pid',
        ),
    ]
