# Generated by Django 3.1.7 on 2021-04-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0028_auto_20210407_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='pid',
            new_name='id',
        ),
    ]
