# Generated by Django 3.1.7 on 2021-04-08 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0030_auto_20210407_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cont',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbs.post'),
        ),
    ]
