# Generated by Django 3.1.7 on 2021-04-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0031_auto_20210408_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='cont',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cont',
            name='type',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
