# Generated by Django 3.1.7 on 2021-04-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0033_auto_20210408_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cont',
            name='pid',
            field=models.CharField(max_length=50),
        ),
    ]
