# Generated by Django 3.1.7 on 2021-04-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0035_cont_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pid',
            new_name='paid',
        ),
        migrations.AddField(
            model_name='post',
            name='cs',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='ls',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
