# Generated by Django 3.1.7 on 2021-04-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0037_like_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
