# Generated by Django 3.1.7 on 2021-04-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0039_auto_20210409_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='paid',
            field=models.CharField(max_length=100),
        ),
    ]
