# Generated by Django 3.1.7 on 2021-04-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0040_auto_20210410_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='pid',
            field=models.CharField(max_length=100),
        ),
    ]
