# Generated by Django 3.1.7 on 2021-04-10 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0041_auto_20210410_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='paid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbs.page'),
        ),
        migrations.AlterField(
            model_name='like',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbs.post'),
        ),
    ]
